<?php

namespace App\Constants;

class Prescriptions
{
	const INTERNAL_MEDICAL_PRESCRIPTION = 1;
	const EXTERNAL_MEDICAL_PRESCRIPTION = 2;
	const TEST_PRESCRIPTION = 3;

	const NEW_PRESCRIPTION = 1;
	const PENDING_PRESCRIPTION = 2;
	const CANCELED_PRESCRIPTION = 3;
	const CONFIRMED_PRESCRIPTION = 4;
	const PAID_PRESCRIPTION = 5;
	const ISSUED_PRESCRIPTION = 6;
}